const countryToCode = {
  "France": "🇫🇷",
  "Allemagne": "🇩🇪",
  "Ukraine": "🇺🇦",
  "États-Unis": "🇺🇸",
  "Japon": "🇯🇵",
  "Belgique": "🇧🇪",
  "Italie": "🇮🇹",
  "Chine": "🇨🇳",
  "Royaume-Uni": "󠁧󠁢󠁥󠁮🇬🇧",
  "Pérou": "🇵🇪",
  "Mexique": "🇲🇽",
  "Jordanie": "🇯🇴",
  "Brésil": "🇧🇷",
  "Égypte": "🇪🇬",
  "Turquie": "🇹🇷",
  "Grèce": "🇬🇷",
  "Irak": "🇮🇶",
  "Groenland": "🇬🇱",
  "Inde": "🇮🇳",
  "Vietnam": "🇻🇳",
  "Russie": "🇷🇺",
  "RDC": "🇨🇬",
  "Chili": "🇨🇱",
  "Iran": "🇮🇷",
  "Oman": "🇴🇲",
  "Indonésie": "🇮🇩",
  "Népal": "🇳🇵",
  "Corée du Nord": "🇰🇵",
  "Corée du Sud": "🇰🇷",

  // ZONES SPÉCIALES OU PAYS MULTIPLES
  "Corée du Nord / Corée du Sud": "🇰🇵/🇰🇷",
  "Iran / Oman": "🇮🇷/🇴🇲",
  "Népal/Chine": "🇳🇵/🇨🇳",
  "Groenland Est (Zone militaire)": "⚠️",
  "Zone démilitarisée (DMZ) Corée": "🇰🇵/🇰🇷",
  "Mont Everest (Zone de la 'death zone')": "🇳🇵/🇨🇳",

  // ZONES OCÉANS / MERS / PAS DE NATION
  "Océan Atlantique": "🌊",
  "Océan Pacifique": "🌊",
  "Océan Indien": "🌊",
  "Océan Austral": "🌊",
  "Océan Arctique": "❄️",
  "Mer Méditerranée": "🌊",
  "Mer Noire": "🌊",
  "Mer de Chine méridionale": "🌊",
  "Mer Rouge": "🌊",
  "Mer du Nord": "🌊",
  "Mer des Caraïbes": "🏝️",
  "Mer de Béring": "🌊",
  "Mer d’Okhotsk": "🌊",
  "Mer Baltique": "🌊",
  "Fosse des Mariannes": "🧭",
  "Triangle des Bermudes": "🏴‍☠️",
  "Le Triangle des Bermudes": "🏴‍☠️",
  "Zone de Fukushima (Océan Pacifique)": "☢️"
};

export default countryToCode;