const countryToCode = {
  "France": "FR",
  "Allemagne": "DE",
  "Ukraine": "UA",
  "États-Unis": "US",
  "Japon": "JP",
  "Belgique": "BE",
  "Italie": "IT",
  "Chine": "CN",
  "Royaume-Uni": "GB",
  "Pérou": "PE",
  "Mexique": "MX",
  "Jordanie": "JO",
  "Brésil": "BR",
  "Égypte": "EG",
  "Turquie": "TR",
  "Grèce": "GR",
  "Irak": "IQ",
  "Groenland": "GL",
  "Inde": "IN",
  "Vietnam": "VN",
  "Russie": "RU",
  "RDC": "CD",
  "Chili": "CL",
  "Iran": "IR",
  "Oman": "OM",
  "Indonésie": "ID",
  "Népal": "NP",
  "Corée du Nord": "KP",
  "Corée du Sud": "KR",

  // ZONES SPÉCIALES OU PAYS MULTIPLES
  "Corée du Nord / Corée du Sud": "🇰🇵/🇰🇷",     // emoji duo
  "Iran / Oman": "🇮🇷/🇴🇲",
  "Népal/Chine": "🇳🇵/🇨🇳",
  "Groenland Est (Zone militaire)": "⚠️",
  "Zone démilitarisée (DMZ) Corée": "🇰🇵/🇰🇷",
  "Mont Everest (Zone de la 'death zone')": "🇳🇵/🇨🇳",

  // ZONES OCÉANS / MERS / PAS DE NATION
  "Océan Atlantique": "🌊",
  "Océan Pacifique": "🌊",
  "Océan Indien": "🌊",
  "Océan Austral": "🌊",
  "Océan Arctique": "❄️",
  "Mer Méditerranée": "🌊",
  "Mer Noire": "🌊",
  "Mer de Chine méridionale": "🌊",
  "Mer Rouge": "🌊",
  "Mer du Nord": "🌊",
  "Mer des Caraïbes": "🏝️",
  "Mer de Béring": "🌊",
  "Mer d’Okhotsk": "🌊",
  "Mer Baltique": "🌊",
  "Fosse des Mariannes": "🧭",
  "Triangle des Bermudes": "🏴‍☠️",
  "Le Triangle des Bermudes": "🏴‍☠️",
  "Zone de Fukushima (Océan Pacifique)": "☢️"
};

export default countryToCode;